# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Status 

on: push

jobs:
  java_tests:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Build with Ant
      uses: coactions/setup-xvfb@v1
      with:
        run: |
          set -e
          ant -noinput -buildfile build.xml
          cat tempsEquipes.json
